source 'https://rubygems.org'
ruby '2.3.4'
gem 'rails', '5.0.0'
gem 'pg'
gem 'bootstrap-sass', '~> 3.3.5'
gem 'sass-rails', '>= 3.2'
gem 'jquery-rails'
gem 'uglifier', '>= 1.3.0'
gem 'responders'
gem 'faker'
gem 'populator'
gem 'react-rails'

group :development, :test do
  gem 'rspec-rails'
  gem 'launchy'
  gem 'pry-rails'
  gem 'capybara'
  gem 'database_cleaner'
end
